USE mysql;

CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'ekraujin'@'%' IDENTIFIED BY '1111';
GRANT ALL PRIVILEGES ON wordpress.* TO 'ekraujin'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root1111';