USE mysql;
CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'ekraujin'@'%' IDENTIFIED BY 'ek';
GRANT ALL PRIVILEGES ON wordpress.* TO 'ekraujin'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'ek42';